### ISSUE TITLE
`reference-section-title` -> `attempt to index a nil value (field 'c')`

### ISSUE THREAD

**Issue by JBGruber** [andrewheiss/quarto-wordcount#3]
I think there might be a bug in the lua script. When I set the option `reference-section-title` (no matter to what), I run into this error:

```
Error running filter /opt/quarto/share/filters/main.lua:
...est/test/_extensions/andrewheiss/wordcount/wordcount.lua:41: attempt to index a nil value (field 'c')
stack traceback:
	...est/test/_extensions/andrewheiss/wordcount/wordcount.lua:59: in global 'remove_all_refs'
	...est/test/_extensions/andrewheiss/wordcount/wordcount.lua:140: in function <...est/test/_extensions/andrewheiss/wordcount/wordcount.lua:131>
	[C]: in ?
	[C]: in method 'walk'
	/opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	/opt/quarto/share/filters/main.lua:449: in local 'callback'
	[string "..."]:1789: in field 'withScriptFile'
	/opt/quarto/share/filters/main.lua:452: in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
stack traceback:
	/opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	/opt/quarto/share/filters/main.lua:449: in local 'callback'
	[string "..."]:1789: in field 'withScriptFile'
	/opt/quarto/share/filters/main.lua:452: in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
```

<details>
 <summary>minimal example</summary>

```
---
title: Some title
author: Some author
date: last-modified
reference-section-title: "References"
format:
  wordcount-html: 
    toc: false
- id: Turing1936
  author:
    - family: Turing
      given: Alan Mathison
  citation-key: Turing1936
  container-title: Journal of Math
  issue: 345–363
  issued:
    - year: 1936
  page: 230–265
  title: On Computable Numbers, with an Application to the Entscheidungsproblem
  type: article-journal
  volume: 58
---

```

Note that it does not  happen when there is no bibliography.
</details>

<details>
 <summary>sessionInfo</summary>

``` r
sessionInfo()
#> R version 4.3.2 (2023-10-31)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: EndeavourOS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/libblas.so.3.11.0 
#> LAPACK: /usr/lib/liblapack.so.3.11.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=nl_NL.UTF-8        LC_COLLATE=en_GB.UTF-8    
#>  [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_GB.UTF-8   
#>  [7] LC_PAPER=nl_NL.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       
#> 
#> time zone: Europe/Busingen
#> tzcode source: system (glibc)
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] styler_1.10.1     digest_0.6.33     fastmap_1.1.1     xfun_0.40        
#>  [5] magrittr_2.0.3    glue_1.6.2        R.utils_2.12.2    knitr_1.42       
#>  [9] htmltools_0.5.6   rmarkdown_2.21    lifecycle_1.0.3   cli_3.6.1        
#> [13] R.methodsS3_1.8.2 vctrs_0.6.3       reprex_2.0.2      withr_2.5.1      
#> [17] compiler_4.3.2    R.oo_1.25.0       R.cache_0.16.0    purrr_1.0.2      
#> [21] rstudioapi_0.15.0 tools_4.3.2       evaluate_0.21     yaml_2.3.7       
#> [25] rlang_1.1.1       fs_1.6.3
```

<sup>Created on 2023-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

</details>

**Comment by andrewheiss** [comment]
Ah, good catch! It turns out that I was trying to be too fancy with counting words for the references section. In theory, the filter was supposed to identify the bibliography heading and remove it and count it as part of the references section count.

In practice, though, it never actually worked, in part because there are multiple ways to get a bibliography heading:

1: A heading at the end of the document:

````
---
title: Some title
author: Some author
---

Blah blah [@some-citation].

# A fancy bibliography
````

2: A heading followed by a special div:

````
---
title: Some title
author: Some author
---

Blah blah [@some-citation].

# A fancy bibliography

::: {#refs}
:::

More stuff
````

3: Setting `reference-section-title`:

````
---
title: Some title
author: Some author

reference-section-title: "A fancy bibliography"
---

Blah blah [@some-citation].
````

In all three cases, there's no way to identify that the "A fancy bibliography" heading is the heading for the references section. The code that was breaking tried to, and I think at one point once upon a time pandoc added some metadata about the heading's status as a references header, but that's no longer the case.

So I fixed it in https://github.com/andrewheiss/quarto-wordcount/commit/f94fa50974dd8f231b7d80abc764f4c458d76dcd by just not trying anymore :)

The reference heading still gets counted, just as part of the main body instead of the references section

So this document:

````
---
title: Some title
author: Some author
date: last-modified

reference-section-title: "A fancy bibliography"

format:
  wordcount-html: 
    toc: false

references:
- id: Turing1936
  author:
    - family: Turing
      given: Alan Mathison
  citation-key: Turing1936
  container-title: Journal of Math
  issue: 345–363
  issued:
    - year: 1936
  page: 230–265
  title: On Computable Numbers, with an Application to the Entscheidungsproblem
  type: article-journal
  volume: 58
---

Blah blah [@Turing1936].
````

Renders like this:

<img width="574" alt="image" src="https://github.com/andrewheiss/quarto-wordcount/assets/73663/0136291c-cd62-4c2f-bb75-26f65afb664b">

&nbsp;

And it gets this word count:

```
28 total words
-----------------------------
7 words in text body
21 words in reference section
```

The 7 words in the text body are `Blah blah (Turing 1936).` (4 words) and `A fancy bibliography` (3 words). The 21 words in the reference section are the `Turing, Alan Mathison ... 230–65.` reference.
